version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    volumes:
      - ./api/db.json:/app/db.json
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mongo
    restart: unless-stopped
    depends_on:
      - mongo

  queue_system:
    build:
      context: ./queue_system
      dockerfile: Dockerfile
    container_name: queue_system
    env_file:
      - ./queue_system/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mongo
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daniel
      - MONGO_INITDB_ROOT_PASSWORD=daniel
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
